### ISSUE TITLE
useMemo always recomputing

### ISSUE THREAD

**Issue by dyslexicsteak** [LastTalon/matter-hooks#18] opened 2023-09-16 20:47 UTC
## Description

useMemo appears not to work.

## Steps to reproduce

1. Prepare your Matter boilerplate.
2. Register a system that uses useMemo with a constant in the dependencies table or an empty dependencies table, a constant in the discriminator, and a print in the callback.
3. Observe the print being called each and every time without fail.

My (far from minimal) repro: [umdbg.zip](https://github.com/LastTalon/matter-hooks/files/12641550/umdbg.zip)

## Expected behavior

The callback should only run — and print — once.

**Comment by LastTalon** [comment] 2023-09-21 18:53
Apologies for the delay, I've been busy with other things. I'll check the repro soon.

**Comment by LastTalon** [comment] 2023-09-25 18:05
I haven't had a chance to actually run this, but it looks like you're calling the hook conditionally. You should avoid this typically because any frame where the hook isn't called it will be cleaned up. It doesn't try to persist the memoized data if it's no longer being called.

In order to try and fix this, you can lift `useMemo` out of the conditional and only use and/or update it when the value of your condition changes (this can be placed in dependency table if this is the behavior you need, but this may not be what you desire in your case).

Let me know if this fixes your issue. Otherwise I can try and provide more information when I do have some time to run this repro.

**Comment by dyslexicsteak** [comment] 2023-09-30 07:32
> You should avoid this typically because any frame where the hook isn't called it will be cleaned up. It doesn't try to persist the memoized data if it's no longer being called.

That is a huge limitation and footgun that needs to be mentioned. I tried to rearchitect it in the following way, but this ends up doing the same if not more work.

```lua
-- ...
local appropriateTween = Hooks.useMemo(function()
	print("useMemo computed")

	return if binaryState.state 
		then 
		TweenService:Create(model.instance, TweenInfo.new(), {
			Position = model.instance.Position + Vector3.new(0, 3, 0),
		}) 
		else
		TweenService:Create(model.instance, TweenInfo.new(), {
			Position = model.instance.Position - Vector3.new(0, 3, 0),
		})
end, {binaryState.state, id}, id)

if Hooks.useChange(binaryState.state, id) then
	appropriateTween:Play()
end
-- ...
```

This is because when the state changes it has to recompute (the state only changes when you click the part and is the only time the value is actually used). The alternative is to make a `ReversingTween` component with 2 tweens as data initialised on spawn, but I've been trying to avoid that as I would never query for that component on its own and it seems like unnecessarily exposing the World and its archetype graph to a small implementation detail that makes it more complex for naught.

**Comment by LastTalon** [comment] 2023-09-30 18:17
> That is a huge limitation and footgun that needs to be mentioned.

This is a limitation of all hooks. It's talked about in the matter docs. Topologically aware hooks are actually somewhat unique in that they can be called conditionally and typical hooks must be called at the top level always.

I don't really feel that special education on hook usage should be done in this library; it expects that you know these limitations of hooks already and is meant as a collection of useful hooks. If you have a suggestion about how to explain that better you can make that over on the [Matter issues](https://github.com/evaera/matter/issues) page, or in Discord if you like. 

> I tried to rearchitect it in the following way, but this ends up doing the same if not more work.

There are lots of people on Discord who can try and help with this sort of thing. For now I'm closing this issue since it seems like the hook is working as intended though.

**Closed as not planned by LastTalon** 2023-09-30 18:17 UTC
Labels: bug
